### ISSUE TITLE
dataset/nuscenes/metadata/val_gt_tforms.npy may uploaded error

### ISSUE THREAD

**Issue by yxy749980346** [yuvalH9/UMERegRobust#1]
Hello.I found the dataset/nuscenes/metadata/val_gt_tforms.npy may be uploaded error. It seems same as the dataset/nuscenes/metadata/val_metadata.npy. Could you reupload this file or you can tell me how to get it? Thanks!

**Comment by yuvalH9** [comment]
@yxy749980346  thanks for letting me know!
I replaced the file to the correct one.
