### ISSUE TITLE
复现出现了一下问题，想问一下应该怎么解决呢？

### ISSUE THREAD

**Issue by ronan222222** [yuvalH9/UMERegRobust#5]
复现出现了一下问题，想问一下应该怎么解决呢？Traceback (most recent call last):   File "train_coloring.py", line 425, in <module>     train_one_epoch(epoch, dloader_train, model, point_wise_loss_fn, optimizer, summary_writer)   File "train_coloring.py", line 44, in train_one_epoch     src_feat = torch.stack(model(src_stensor).decomposed_features, dim=0)   File "/home/yrn/anaconda3/envs/peizhui/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl     return forward_call(*input, **kwargs)   File "/home/yrn/UMERegRobust-master/models.py", line 557, in forward     out_s1 = self.conv1(x)   File "/home/yrn/anaconda3/envs/peizhui/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl     return forward_call(*input, **kwargs)   File "/home/yrn/anaconda3/envs/peizhui/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/MinkowskiConvolution.py", line 314, in forward     outfeat = self.conv.apply(   File "/home/yrn/anaconda3/envs/peizhui/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg/MinkowskiEngine/MinkowskiConvolution.py", line 72, in forward     return fw_fn( MemoryError: std::bad_alloc: cudaErrorMemoryAllocation: out of memory希望大佬帮忙解答一下

**Comment by yuvalH9** [comment]
duplicate #6
